repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: "^.idea/.*$"
      - id: forbid-new-submodules
      - id: mixed-line-ending
      # - id: no-commit-to-branch
      # args: [--branch, main]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.44.0
  #   hooks:
  #     - id: eslint
  #       additional_dependencies:
  #         - eslint@8.44.0
  #         - react-scripts
