const CONFIG = {
  submit: {
    runTime: {
      type: "text_input",
      title: "Total Time",
      id: "runTime",
      required: true,
      placeholder: "1:30:00",
      help: "Time when you see the flash/hear the crack after killing Kefka.",
    },
    ktStartTime: {
      type: "text_input",
      title: "KT Start Time",
      id: "ktStartTime",
      required: false,
      placeholder: "1:00:00",
      help: "Time after you pick your party to enter Kefka's Tower.",
    },
    kefkaTime: {
      type: "text_input",
      title: "Kefka Start Time",
      id: "kefkaTime",
      required: false,
      placeholder: "1:20:00",
      help: "Time when your final party steps on the final switch.",
    },
    flagset: {
      type: "dropdown",
      title: "Flagset",
      id: "flagset",
      required: false,
      enumName: "Flagset",
    },
    chars: {
      type: "checkbox",
      title: "Characters",
      id: "chars",
      required: true,
      enumName: "Character",
    },
    abilities: {
      type: "checkbox",
      title: "Abilities",
      id: "abilities",
      required: true,
      enumName: "Ability",
    },
    numOfChars: {
      type: "slider",
      title: "Number of Characters",
      id: "numOfChars",
      required: true,
      min: "1",
      max: "14",
      step: "1",
      startingValue: "3",
      help: "",
    },
    numOfEspers: {
      type: "slider",
      title: "Number of Espers",
      id: "numOfEspers",
      required: true,
      min: "0",
      max: "27",
      step: "1",
      startingValue: "0",
      help: "",
    },
    numOfDeadChecks: {
      type: "slider",
      title: "Number of Dead Checks",
      id: "numOfDeadChecks",
      required: true,
      min: "0",
      max: "11",
      step: "1",
      startingValue: "0",
      help: "Use the Track screen as a base.  Add 1 for every dead check you reset/warped out of, subtract 1 for non-progress checks (Fanatics Tower Chest, Lone Wolf Moogle Room, Kefka's Tower Cell Beast, Narshe Weapon Shop Mine) and for every dragon.",
    },
    numOfBosses: {
      type: "slider",
      title: "Number of Bosses",
      id: "numOfBosses",
      required: true,
      min: "0",
      max: "39",
      step: "1",
      startingValue: "0",
    },
    numOfChests: {
      type: "slider",
      title: "Number of Chests",
      id: "numOfChests",
      required: false,
      min: "0",
      max: "255",
      step: "1",
      startingValue: "0",
      help: "Entering 0 chests = N/A",
    },
    skip: {
      type: "toggle",
      title: "Skip",
      id: "skip",
      required: true,
      help: "Whether you skipped straight to the statues in Kefka's Tower.",
    },
    dragons: {
      type: "checkbox",
      title: "Dragon Location",
      id: "dragons",
      required: true,
      subtitleText: "Where you fought a dragon",
      help: "Selecting none indicates that you took 0 dragon fights.",
      enumName: "Dragon",
    },
    finalBattle: {
      type: "checkbox",
      title: "Final Battle Preperation",
      id: "finalBattle",
      required: true,
      help: "Selecting none indicates no special prep for the final battle.",
      enumName: "FinalBattleTrait",
    },
    highestLevel: {
      type: "slider",
      title: "Highest Level",
      id: "highestLevel",
      required: true,
      min: "3",
      max: "99",
      step: "1",
      startingValue: "3",
      help: "Highest level character.",
    },
    superBalls: {
      type: "toggle",
      title: "Superballs",
      id: "superBalls",
      required: true,
      help: "Whether you bought Superballs.",
    },
    egg: {
      type: "toggle",
      title: "Exp. Egg",
      id: "egg",
      required: true,
      help: "Did you find an Exp. Egg and get value out of it?",
    },
    coliseum: {
      type: "toggle",
      title: "Coliseum",
      id: "coliseum",
      required: true,
      help: "If you went to the coliseum.",
    },
    thief: {
      type: "dropdown",
      title: "Tzen Thief",
      id: "thief",
      required: true,
      enumName: "Thief",
    },
    auction: {
      type: "slider",
      title: "Auction House",
      id: "auction",
      required: true,
      min: "0",
      max: "2",
      step: "1",
      startingValue: "0",
      help: "Number of espers bought at the Auction House.",
    },
  },
  submitFormat: {
    // This is the format of panels on the submission page.  The children of the colums are the cards
    // and their children are the fields in those cards.
    columnLeft: {
      runTime: {
        title: "Run Time",
        children: ["runTime", "ktStartTime", "kefkaTime", "flagset"],
      },
      startingParty: {
        title: "Starting Party",
        children: ["chars", "abilities"],
      },
    },
    columnRight: {
      progress: {
        title: "Progress",
        children: ["numOfChars", "numOfEspers", "dragons", "skip"],
      },
      checks: {
        title: "Checks and Misc",
        children: [
          "numOfDeadChecks",
          "numOfBosses",
          "numOfChests",
          "auction",
          "thief",
        ],
      },
      offense: {
        title: "Offense",
        children: [
          "finalBattle",
          "highestLevel",
          "superBalls",
          "egg",
          "coliseum",
        ],
      },
    },
  },
};

export default CONFIG;
